TARGET     = $(R00TLeInstall)/lib/libInputManager.so
OBJS       = InputManager.o InputManagerDictionary.o
TEMP	=
LIBDIR   = $(R00TLeInstall)/lib/
SPECIALLIBS=$(addprefix -l,$(TEMP)) -L$(LIBDIR)
include $(R00TLeInstall)/src/common.mk
