TARGET     = $(R00TLeInstall)/lib/libScalers.so
OBJS       = LendaScalers.o S800Scalers.o Scalers.o ScalersDictionary3.o
SPECIALHEADERS = LendaScalers.hh S800Scalers.hh


include ../common.mk


test:
	@echo $(OBJS)